name: Emoji PR number

on:
  pull_request:
    types: [opened]

jobs:
  add-tada:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Adds hooray emoji when adding PR 10000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the pull request number from the event data
          PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
          # Check if the PR number is 10000
          if [[ "$PR_NUMBER" -eq 10000 ]]; then
            # Add the hooray emoji to the pull request
            curl -H "Authorization: token $GITHUB_TOKEN" -X POST \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/reactions" \
              -d '{"content": "hooray"}'
          fi
